"""
Django settings for tes project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/

"""


import os # load the os module
from pathlib import Path # load the path
from dotenv import load_dotenv # load the dotenv

load_dotenv() 

BASE_DIR = Path(__file__).resolve().parent.parent # getting the dir from the productio na dnthe dvlopemenr 

SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "django-insecure-change-me-in-production") # secturt key used for the https i think 

DEBUG = os.environ.get("DEBUG", "False") == "True" # why is it true 

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "*").split(",")


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin" , # for creating and manage the users
    "django.contrib.auth" , # controlling the usets
    "django.contrib.contenttypes" , # for genric refrence to the db 
    "django.contrib.sessions" , # for manageing the sessions  
    "django.contrib.messages" , # for sending the messages to the users 
    "django.contrib.staticfiles" , # fir servingt he static files to theclint (is it include the temolate too )
    "cloudinary_storage" ,
    "cloudinary" ,
    "accounts" ,
    "core" ,
    "products" ,
    "cart" ,
    "orders" ,
    "reviews" ,
    "tailwind" ,
    "theme" ,
]




MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware", # secuirty middle ware for handling http->https convertion
    "whitenoise.middleware.WhiteNoiseMiddleware", # for serviceing the sttac file on the production 
    "django.contrib.sessions.middleware.SessionMiddleware", # session handler 
    "django.middleware.common.CommonMiddleware",  #utitlity middle ware 
    "django.middleware.csrf.CsrfViewMiddleware", # for validating each of the request 
    "django.contrib.auth.middleware.AuthenticationMiddleware", #for auth 
    "django.contrib.messages.middleware.MessageMiddleware", # for messages 
    "django.middleware.clickjacking.XFrameOptionsMiddleware", # for making sure i can't add this web inside a another web 
] # now my question does the order in which we do the middleware cause any issue 



# for managignt he main urs
ROOT_URLCONF = "tes.urls"



# what does this do 
# this does the following that  is this tells the django where to find the templates 
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates" , # this is a template engine right  we can use 
        "DIRS": [BASE_DIR / "templates"] ,# tell to look inside the templates (in that folder  )inside the each app folder
        "APP_DIRS": True , # tell to look inside the templates in inside each of the folder
        "OPTIONS": { # what dara are injectted to each of the temolated by default 
            "context_processors": [
                "django.template.context_processors.request" ,
                "django.contrib.auth.context_processors.auth" ,
                "django.contrib.messages.context_processors.messages" ,
                "cart.cart.cart_context" ,
                "tes.context_processors.theme_colors" ,
                "core.context_processors.contact_info" ,
            ] ,
        } ,
    } ,
]

# for tellin which applcaion are we using 
WSGI_APPLICATION = "tes.wsgi.application"



import dj_database_url 

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_URL = os.environ.get("DATABASE_URL")

if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.config(
            default=DATABASE_URL, 
            conn_max_age=600, # whar does param means 
            conn_health_checks=True, # what does this param means 
        )
    }

else:
    # Fallback to SQLite for local development and is it for each of the application or just e root folder 
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
# session engine + other things 
# why doe we need a session engine and what is a session engine 
SESSION_ENGINE = "django.contrib.sessions.backends.signed_cookies"
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SAMESITE = "Lax"


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization what does this even meand and why does this be usefull for us 
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
# can i ave the stauc in my desired files 
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Django 6.0-compatible storage configuration what is the differnce btw the storage and the database ?
# Cloudinary handles media (uploaded files), WhiteNoise handles static files
STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": (
            "whitenoise.storage.CompressedStaticFilesStorage"
            if not DEBUG
            else "django.contrib.staticfiles.storage.StaticFilesStorage"
        ), # why is this written in this format?  and what is whitenoise? 
    },
}

# UPI Payment Configuration okay im giving the data  here from the env but how does these data are given tot he application 
UPI_ID = os.environ.get("UPI_ID", "gpzstore@oksbi")
PAYEE_NAME = os.environ.get("PAYEE_NAME", " SS Electronincs")

# Google Sheets Sync — Apps Script Web App URL
GOOGLE_SCRIPT_URL = os.environ.get("GOOGLE_SCRIPT_URL", "")

# Cloudinary — Cloud Storage for uploaded files (fixes Vercel read-only filesystem)
# django-cloudinary-storage reads CLOUDINARY_URL from the environment automatically

CART_SESSION_ID = "cart" # why do we need one 

# ─── Site Contact Information ───────────────────────────────────────────────
# Single source of truth for contact details used in the footer and contact page.
# Edit these values to update both places at once.
SITE_CONTACT = {
    "phone": os.environ.get("CONTACT_PHONE", "+91 73584 02926"),
    "email": os.environ.get("CONTACT_EMAIL", "sselectronics2503@gmail.com"),
    "address": os.environ.get("CONTACT_ADDRESS", "Tamil Nadu, India"),
    "working_hours": os.environ.get("CONTACT_HOURS", "Mon–Sat: 9 AM – 6 PM"),
    "whatsapp_url": os.environ.get("CONTACT_WHATSAPP_URL", "https://wa.me/qr/HI63QJ2LKIUWL1"),
    "instagram_url": os.environ.get("CONTACT_INSTAGRAM_URL", "https://www.instagram.com/sselectronics25?igsh=YzljYTk1ODg3Zg=="),
}

TAILWIND_APP_NAME = 'theme'

INTERNAL_IPS = [
    "127.0.0.1",
]
# can i do the same for all the application in this setting or just for this one only 

JAZZMIN_SETTINGS = {
    "site_title": "SS Eletronics Admin",
    "site_header": "SS Eletronics",
    "site_brand": "SS Eletronics",
    "welcome_sign": "Welcome to SS Eletronics Management",
    "copyright": "SS Eletronics Ltd",
    "search_model": ["auth.User", "products.Product"],
    "show_sidebar": True,
    "navigation_expanded": True,
    "order_with_respect_to": ["auth", "products", "orders", "cart"],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "products.Product": "fas fa-box",
        "products.Category": "fas fa-tags",
        "orders.Order": "fas fa-shopping-cart",
        "cart.Cart": "fas fa-trash",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "changeform_format": "horizontal_tabs",
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-primary",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "pulse",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

# Email Configuration
EMAIL_BACKEND = os.environ.get("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", 587))
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "True") == "True"
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)
ADMIN_EMAIL = os.environ.get("ADMIN_EMAIL", EMAIL_HOST_USER)
