# Generated by Django 6.0.3 on 2026-04-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_payment_screenshot_order_utr_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("upi_qr", "UPI QR")], default="upi_qr", max_length=50
            ),
        ),
    ]
