# Generated by Django 6.0.3 on 2026-04-28 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_tag_alter_category_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="video_url",
        ),
        migrations.AddField(
            model_name="product",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="products/videos/"),
        ),
    ]
