# Generated by Django 6.0.3 on 2026-04-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_remove_product_video_url_product_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="video",
        ),
        migrations.AddField(
            model_name="product",
            name="video_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
